#!/bin/bash
cd "$(dirname "$0")"

VER=$1
ver=`echo $VER | cut -c1-3`

rpm=mongodb-org-server-$VER-1.el8.x86_64.rpm
url=https://repo.mongodb.org/yum/redhat/8/mongodb-org/$ver/x86_64/RPMS

rm -rf $rpm
wget $url/$rpm
rc=$?

if [ "$rc" == "0" ]; then
  sudo rpm -ivh $rpm
  rm $rpm
fi

