#!/bin/bash
cd "$(dirname "$0")"

echo " "
echo "## INSTALL OMNIDB v$1 ############################################"
source getPKMG.sh

if [ "$PKMG" == "yum" ]; then
  echo "not supported yet"
else
  sudo apt install omnidb.deb
fi

