#!/bin/bash
cd "$(dirname "$0")"

echo " "
echo "## INSTALL REDIS ##########################################"
source getPKMG.sh


if [ "$PKMG" == "yum" ]; then
  sudo yum install -y epel-release
  sudo yum install -y redis
  sudo systemctl start redis
  sudo systemctl enable redis
else
  sudo apt install -y  redis-server
  sudo cp redis.conf /etc/redis/.
  sudo systemctl restart redis
fi
