#!/bin/bash
cd "$(dirname "$0")"

if [ "$1" == "" ]; then
  echo "ERROR: version num parm required"
  exit 1
fi

echo " "
echo "## INSTALL KAFKA v$1 ######################################"
source getPKMG.sh

set -x

kafkaV=$1
kafkaD=kafka_2.13-$kafkaV
kafkaF=$kafkaD.tgz
URL=https://mirrors.ocf.berkeley.edu/apache/kafka

rm -rf $kafkaF
wget $URL/$kafkaV/$kafkaF
tar xzf $kafkaF

sudo rm -rf /usr/local/kafka
sudo mv $kafkaD /usr/local/kafka

sudo cp kafka.service     /etc/systemd/system/.
rm -rf $kafkaF

sudo systemctl daemon-reload
sudo systemctl start kafka

