#!/bin/bash
cd "$(dirname "$0")"

echo " "
echo "## INSTALL PGPOOL2 #######################################"
source getPKMG.sh

minor_ver=4.2.3
major_ver=4.2

repo=https://www.pgpool.net/yum/rpms/$major_ver/redhat/rhel-8-x86_64
rpm=pgpool-II-pg13-$minor_ver-1pgdg.rhel8.x86_64.rpm

sudo yum install -y $repo/$rpm

