#!/bin/bash
cd "$(dirname "$(readlink -f "$0")")"

yumInstall () {
  echo "Not yet!"
  exit 1
}

aptInstall () {
  sudo apt update
  sudo apt upgrade -y
  sudo apt install -y etcd
}

################## MAINLINE #####################################

source getPKMG.sh
echo "## INSTALLING ETCD w/ $PKMG ###############################"

if [ "$PKMG" == "yum" ]; then
  yumInstall
else
  aptInstall
fi

exit 0

