#!/bin/bash
cd "$(dirname "$(readlink -f "$0")")"

yumRemove () {
  echo "Not yet!"
  exit 1
}

aptRemove () {
  sudo apt remove  -y etcd
}

################## MAINLINE #####################################

source getPKMG.sh
echo "## INSTALLING ETCD w/ $PKMG ###############################"

if [ "$PKMG" == "yum" ]; then
  yumRemove 
else
  aptRemove 
fi

exit 0

