#!/bin/bash
cd "$(dirname "$0")"

secureInstallation() {
  sudo mysql -e "UPDATE mysql.user SET Password=(‘password’) WHERE User=’root’;"
  sudo mysql -e "DELETE FROM mysql.user WHERE User=’root’ AND Host NOT IN (‘localhost’, ‘127.0.0.1’, ‘::1’);"
  sudo mysql -e "DELETE FROM mysql.user WHERE User=”;"
  sudo mysql -e "DROP DATABASE test;"
  sudo mysql -e "FLUSH PRIVILEGES;"
}

echo " "
echo "## INSTALL MARIADB ##############################################"
source getPKMG.sh
if [ "$PKMG" == "yum" ]; then
  sudo cp MariaDB.repo /etc/yum.repos.d/.
  sudo yum install -y MariaDB-server
  ##secureInstallation
  exit
fi


## APT #########################################################
sudo apt update -y
sudo apt -y install software-properties-common
sudo apt-key adv --fetch-keys 'https://mariadb.org/mariadb_release_signing_key.asc'
sudo add-apt-repository 'deb [arch=amd64] http://mariadb.mirror.globo.tech/repo/10.5/ubuntu focal main'
sudo apt update -y
sudo apt install -y mariadb-server mariadb-client
##secureInstallation
