#!/bin/bash
cd "$(dirname "$0")"


if [ "$1" == "" ]; then
  echo "ERROR: version num parm required"
  exit 1
fi

ver=$1

echo " "
echo "## INSTALL PGADMIN 4 v$ver #######################################"
source getPKMG.sh

if [ "$PKMG" == "yum" ]; then
  echo "not supported yet"
else
  sudo apt install pgadmin4.deb
fi

