#!/bin/bash
cd "$(dirname "$0")"

echo " "
echo "## INSTALL PATRONI ##############################################"
source getPKMG.sh

## DEB #########################################################
sudo apt update -y
sudo apt install -y etcd haproxy

pip3 install -r requirements.txt

