#!/bin/bash
cd "$(dirname "$(readlink -f "$0")")"

yumInstall () {
  sudo yum -y  install epel-release curl wget

  sudo yum -y update --nobest

  curl -s https://packagecloud.io/install/repositories/rabbitmq/$rabbit/script.rpm.sh | sudo bash

  sudo yum makecache -y --disablerepo=* --enablerepo=rabbitmq_$rabbit
  sudo yum -y install $rabbit

  sudo systemctl enable --now $rabbit
}

aptInstall () {
  sudo apt update
  sudo apt upgrade -y
  sudo apt install apt-transport-https -y
  wget -O- https://dl.bintray.com/rabbitmq/Keys/rabbitmq-release-signing-key.asc | sudo apt-key add -
  wget -O- https://www.rabbitmq.com/rabbitmq-release-signing-key.asc | sudo apt-key add -

  cmd="deb https://dl.bintray.com/rabbitmq-erlang/debian focal erlang-22.x"
  echo "$cmd" | sudo tee /etc/apt/sources.list.d/rabbitmq.list

  sudo apt update
  sudo apt install -y $rabbit

}

################## MAINLINE #####################################

source getPKMG.sh
echo "## INSTALLING RABBITMQ w/ $PKMG ###########################"

export  rabbit=rabbitmq-server

if [ "$PKMG" == "yum" ]; then
  yumInstall
else
  aptInstall
fi

exit 0

